name: CI-Rust

on:
  push:
    branches: [ "main" ]
    paths: 
    - "**.rs"
  pull_request:
    branches: [ "main" ]
    paths: 
    - "**.rs"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name : Format
        run : make format_rust
      - name: Lint
        run: make lint_rust
      - name: Archive and Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ml_pipeline-artifacts
          path: ${{ github.workspace }}
        
      - name: Save to repository
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo GH_TOKEN: "${GH_TOKEN}"
          git config --global user.name 'github-actions'
          git config --local user.email "action@github.com"
          git add .
          git commit -m "Performed Rust CI" || echo "ignore commit failure, proceed"
          git push